_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 3
                - 13
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 139
epochs:
    value: 50
learning_rate:
    value: 0.0001
model:
    value: main_classification
warmup_steps:
    value: 1000
